[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && yarn install --frozen-lockfile",
  "cd frontend && yarn build"
]

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"